### ISSUE TITLE
【バグ】#2542)html 書き換え脆弱性対応(テンプレート画面以外)

### ISSUE THREAD

**Issue by mcms-cm** [mcms-cm/dev#16]
影響範囲調査中

**Comment by haru0920** [comment]
対応方法決定
詳細はtrac参照

**Comment by haru0920** [comment]
本件バグではなく、機能改善のフローに乗せるべきではないか、という相談をさせてください

**Comment by mcms-cm** [comment]
今回の修正対象は配信リスト画面、メール登録画面で修正パッチは無し、6.4のパッケージでリリース。
パッケージテスト時に、ＳＩ側と事前に作業範囲を決める必要がある

**Comment by mcms-cm** [comment]
V6.4にマージ済み
