### ISSUE TITLE
【パッケージ】bonoサーバdmailモニター環境設定

### ISSUE THREAD

**Issue by mcms-cm** [mcms-cm/dev#46]
bonoサーバdmailモニター環境設定

**Comment by haru0920** [comment]
リレーモニター部分以外完了

**Comment by haru0920** [comment]
bono環境にgccが入っておらず、redhat環境のためyumで入れることもできない面倒な状況。
centOSを入れて対応する！

**Comment by haru0920** [comment]
対応完了
リレーモニタ画面も参照可
