### ISSUE TITLE
【運用】daily_click.datのリカバリーツール

### ISSUE THREAD

**Issue by mcms-cm** [mcms-cm/dev#55]
=【内容】=
[経緯]
4/5 日本経済新聞社様で以下のような問題が発生しました。
前提：CM5.5.1からCM6.1.0に環境移行しています。
旧環境で予約登録した配信を新環境で配信後、レポーティングで日別クリック分析パートが
生成されなかった問題が発生しました。
原因は、daily_click.dat が更新されなかったため
対応として、click.datがある場合に、正常な状態に復旧できるツールを提供してほしいとのことでした
[作成する意義]
としては、なんらかの状態でデータの表示不具合がある場合に、現状では、手間がかかる＆制約が多い。ので簡単に復旧できるutility tool的なものがあれば、我々も助かる。
DataRecoveryToolの第一弾としてこの現象のものを解消する小さなプログラムの作成がよい。
[仕様というかイメージ]
提供する機能：
daily_click.datがなんらかの問題でデータが更新されていない場合に、手動で強制的に復旧し正常状態に戻す
コマンドイメージ
# source /opt/cm/conf/im_env_bash
# recovery_daily_click ${mailidx}
[検討してほしいとこ]
1－復旧されるものは原則、daily_click.dat ?　仕組みがわかっていないので他にも想定されるものがあれば提示してほしい。
2－検知する期間がクリック期間などを過ぎた場合でも正常になれること
3－DBのバックアップがある場合は、テーブルにデータを流し込めること

**Comment by mcms-cm** [comment]
１）
A)mailidxの指定は複数できるようにする
例)
recovery_daily_click 33 44

B)一旦、daily_click.datをrenameして(daily_click.dat.yyymmdd)新しく作成する

2)im_click_[$mailidx$]の復旧
 A)checkinsertの引数指定(mailidx)でできるか確認後、方法検討

**Comment by mcms-cm** [comment]
C言語で作成する予定
今週中に修正予定

**Comment by htanaka1977** [comment]
recovery_daily_click (daily_click.dat)の復旧プログラム完成

**Comment by mcms-cm** [comment]
チェさんが単体テスト中
