### ISSUE TITLE
【運用】開発チームサーバ整理

### ISSUE THREAD

**Issue by mcms-cm** [mcms-cm/dev#59]
V6.4環境に向け開発チームサーバ整理

**Comment by mcms-cm** [comment]
変更点をレビュー予定

**Comment by nimura-tomoyuki** [comment]
6.4のシステム要件に変更がある場合は、SIチームにも共有願います。こちらも
それにあわせて環境を整備していく方向にします。


事前に必要なlibraryの追加、事前に設定が必要なOSの設定、ベースとなるOSなどなど。
