### ISSUE TITLE
【カスタマイズ】楽天カード様向け承認権限追加

### ISSUE THREAD

**Issue by mcms-cm** [mcms-cm/dev#79]
ASPの顧客の楽天カード様向け承認権限追加機能開発

スケジュール
開発：５月９日～１３日
単体テスト＆パッチリリース：５月１６～２０日

\\mcms\技術本部\000_ClickM@iler\800_おっさん\クライアント\楽天カード

**Comment by ycchoi** [comment]
開発完了
テスト項目書作成完了
